### ISSUE TITLE
Add support back for AWS ELB policies, VPC peering connections and hosted zones

### ISSUE THREAD

**Issue by misg** [nccgroup/ScoutSuite#298]
Some resources were removed during refactoring #183 but they were displayed in Scout Suite reports and thus potentially useful (and used). They should be back.

- [x] ~~`peering_connections`, removed in #273.~~ (**Brought back in #344.**)
- [x] `elb_policies` resources, removed in #257. (**In progress, #358.**)
- [x] `hosted_zones` resources, removed in #267.

**Comment by j4v** [comment]
Implemented in `develop`.

**Comment by j4v** [comment]
Closing as this is implemented in `master`.
